### ISSUE TITLE
Foundation Concepts: 2 typos

### ISSUE THREAD

**Issue by LaPolice** [typesupply/opentype-feature-intro#12]
After reading the whole cookbook with interest, thanks a lot for sharing your knowledge and time, I'm reporting (in Critic Markup) two typos in the first ¶ of Foundation Concepts:
Understanding the underlying mechanics of how features work will allow you to carry your vision all the way from how {--the glyphs --} the glyphs look to how the{++y++} behave.

**Comment by typesupply** [comment]
Fixed. Thanks!
